name: Start the release(create release branch)

on:
  workflow_call: {}

# concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  attestations: write
  actions: write
  id-token: write

jobs:
  start:
    name: Start new release candidate
    permissions:
      contents: write
      actions: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
      #   id: gh-app-token
      #   with:
      #     app-id: ${{ vars.GH_APP_ID }}
      #     private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.5.4

      - name: Prepare pre-requisites
        uses: ./.github/actions/prepare

      - run: bash scripts/start.sh
        shell: bash

  # publish:
  #   needs:
  #     - start
  #   uses: ./.github/workflows/publish.yml

